# Generated by Django 5.2 on 2025-04-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionrequest',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='request_type',
            field=models.CharField(choices=[('connection', 'Подключение'), ('address_check', 'Проверка адреса')], default='connection', max_length=20),
        ),
    ]
