# Generated by Django 5.2 on 2025-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_connectionrequest_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='additional_number_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
