# Generated by Django 5.2 on 2025-04-20 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_tariff_additional_number_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='tv_channels',
            field=models.PositiveIntegerField(blank=True, help_text='Количество ТВ-каналов', null=True),
        ),
    ]
