# Generated by Django 5.2 on 2025-04-21 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_tariff_is_megatariff'),
    ]

    operations = [
        migrations.AddField(
            model_name='tariff',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tariffs', to='main.town'),
        ),
    ]
