# Generated by Django 5.2 on 2025-04-21 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tariff_town'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название оборудования')),
                ('description', models.TextField(verbose_name='Описание оборудования')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('rental_period', models.CharField(max_length=50, verbose_name='Срок аренды')),
                ('is_installment', models.BooleanField(default=False, verbose_name='Рассрочка')),
                ('coverage_area', models.CharField(blank=True, max_length=20, null=True, verbose_name='Площадь покрытия')),
                ('image', models.ImageField(upload_to='equipment/', verbose_name='Фото оборудования')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Оборудование',
                'verbose_name_plural': 'Оборудование',
                'ordering': ['-created_at'],
            },
        ),
    ]
