# Generated by Django 5.2 on 2025-04-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_delete_equipment_alter_region_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={},
        ),
        migrations.RenameField(
            model_name='region',
            old_name='equipment_provider',
            new_name='provider',
        ),
        migrations.AlterUniqueTogether(
            name='town',
            unique_together={('name', 'region')},
        ),
    ]
